#!/usr/bin/env bash
# Regenerate deploy/site/llms-full.txt from the docs pages and the skill. Run
# after editing anything under deploy/site/docs; a test checks the result.
set -euo pipefail
cd "$(dirname "$0")/../deploy/site"
{
  printf '# Dungeon Books, everything in one file\n\n'
  printf '> The same content as llms.txt and the pages it links, inlined. Generated by scripts/llms-full.sh from deploy/site/docs; do not edit by hand.\n\n'
  for f in docs/buying.md docs/api.md docs/cli.md docs/ssh.md; do
    cat "$f"
    printf '\n\n---\n\n'
  done
  printf '# Agent skill\n\n```markdown\n'
  cat skill.md
  printf '```\n'
} > llms-full.txt
echo "wrote $(wc -l < llms-full.txt) lines"
