#!/usr/bin/env bash
# Regenerate deploy/site/llms-full.txt from the docs pages and the skill. Run
# after editing anything under deploy/site/docs; a test checks the result.
set -euo pipefail
cd "$(dirname "$0")/../deploy/site"
{
  printf '# Dungeon Books, everything in one file\n\n'
  printf '> The four docs pages and the agent skill, inlined, for an agent that would rather fetch once. The OpenAPI contract is separate at https://shop.dungeonbooks.com/openapi.json. Generated by scripts/llms-full.sh from deploy/site/docs; do not edit by hand.\n\n'
  for f in docs/buying.md docs/api.md docs/cli.md docs/ssh.md; do
    cat "$f"
    printf '\n\n---\n\n'
  done
  # Four backticks, because the skill has a three-backtick block inside it.
  printf '# Agent skill\n\n````markdown\n'
  cat skill.md
  printf '````\n'
} > llms-full.txt
echo "wrote $(wc -l < llms-full.txt) lines"
